version: '3'

volumes:
  multi_vote_bot:
    external: true

services:
  bot:
    image: ratijas/multi_vote_bot

    build: .

    volumes:
      - "multi_vote_bot:/root/.local/share/multi_vote_bot"

    environment:
      - LISTEN=0.0.0.0
      - PORT=80

    env_file:
      - ".env"

    ports:
      - '${PORT:-8080}:80'

    restart: always
